// Generated by CoffeeScript 1.7.1
(function() {
  var Menu, MenuBuilder, MenuItem, SMenu,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  MenuItem = (function() {
    function MenuItem(title) {
      this.title = title;
      this.sousMenus = [];
    }

    return MenuItem;

  })();

  MenuBuilder = (function() {
    function MenuBuilder() {
      this.sousMenus = [];
    }

    MenuBuilder.m = function(title, url, sms) {
      var menu;
      menu = new Menu(title, null, url);
      sms.reduce((function(acc, m) {
        return acc(push(m));
      }), menu.sousMenus);
      return menu;
    };

    MenuBuilder.prototype.menu = function(title, url) {
      var child;
      if (url == null) {
        url = '';
      }
      child = new Menu(title, this, url);
      this.sousMenus.push(child);
      return child;
    };

    MenuBuilder.prototype.mappings = function() {
      return this.sousMenus.reduce({
        url: '',
        title: ''
      });
    };

    MenuBuilder.prototype.breadCrumb = function(url) {
      return 'Accueil / Santé / CMU ou Lamal';
    };

    MenuBuilder.prototype.asHtml = function() {
      return this.sousMenus.reduce((function(acc, m) {
        return acc + m.asHtml();
      }), "");
    };

    return MenuBuilder;

  })();

  Menu = (function(_super) {
    __extends(Menu, _super);

    function Menu(title, parent, url) {
      this.title = title;
      this.parent = parent;
      this.url = url != null ? url : '';
      Menu.__super__.constructor.call(this, this.title);
    }

    Menu.prototype.subM = function(url, title) {
      this.sousMenus.push(new SMenu(title, this, url));
      return this;
    };

    Menu.prototype.menu = function(title) {
      return this.parent.menu(title);
    };

    Menu.prototype.asHtml = function() {
      var smenus;
      smenus = this.sousMenus.reduce((function(acc, m) {
        return acc + m.asHtml() + "\n";
      }), "");
      return '<li><a href=\"\" data-toggle=\"dropdown\">#{@title}</a><ul>' + smenus + '</ul></li>';
    };

    return Menu;

  })(MenuItem);

  SMenu = (function(_super) {
    __extends(SMenu, _super);

    function SMenu(title, parent, url) {
      this.title = title;
      this.parent = parent;
      this.url = url != null ? url : '';
      SMenu.__super__.constructor.call(this, this.title);
    }

    SMenu.prototype.asHtml = function() {
      return "<li><a href='/" + this.url + "/'>" + this.title + "</li>";
    };

    return SMenu;

  })(MenuItem);

  module.exports = MenuBuilder;

}).call(this);

//# sourceMappingURL=index.map
